version: '3'
services:
  eredes_omie:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"  
    networks:
      - e-redes
  firefox:
    image: seleniarm/standalone-firefox:latest
    container_name: firefox
    ports:
      - 4444:4444
      - 7900:7900
    volumes:
      - ../downloads:/home/seluser/Downloads
    shm_size: '2g'
    networks:
      - e-redes
    restart: unless-stopped
networks:
  e-redes:
